# Generated by Django 3.2.25 on 2024-10-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webServer', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
