# Generated by Django 3.2.25 on 2024-11-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pongGame', '0003_alter_gamestats_game_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestats',
            name='games_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='win_rate',
            field=models.FloatField(default=0),
        ),
    ]
