# Generated by Django 3.2.25 on 2024-11-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pongGame', '0005_auto_20241116_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamehistory',
            old_name='enemy',
            new_name='opponent',
        ),
        migrations.RenameField(
            model_name='gamehistory',
            old_name='enemy_score',
            new_name='opponent_score',
        ),
    ]
