# Generated by Django 3.2.25 on 2024-11-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lang_pref',
            field=models.CharField(default='tr_lang', max_length=15),
        ),
    ]
